# Generated by Django 3.1 on 2020-08-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название планеты')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Текст вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=2, verbose_name='Имя кандидата')),
                ('questions', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.questionmodel', verbose_name='Вопрос теста')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя кандидата')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия кандидата')),
                ('email', models.EmailField(max_length=256, verbose_name='Е-мейл')),
                ('planet', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.planetmodel', verbose_name='Планета обитания')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
        migrations.CreateModel(
            name='JediModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя кандидата')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия кандидата')),
                ('planet', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.planetmodel', verbose_name='Планета обучения')),
            ],
            options={
                'verbose_name': 'Джедай',
                'verbose_name_plural': 'Джедаи',
            },
        ),
    ]
