# Generated by Django 3.1 on 2020-08-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='text',
            field=models.TextField(max_length=128, verbose_name='Текст вопроса'),
        ),
    ]
