# Generated by Django 3.1 on 2020-08-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_questionmodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planetmodel',
            options={'verbose_name': 'Планета', 'verbose_name_plural': 'Планеты'},
        ),
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='questions',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='questions',
            field=models.ManyToManyField(max_length=128, to='mainapp.QuestionModel', verbose_name='Вопрос теста'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='unique_code',
            field=models.CharField(max_length=2, verbose_name='Уникальный код'),
        ),
    ]
