# Generated by Django 3.1 on 2020-08-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200823_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadavanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя падавана')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия падавана')),
                ('age', models.PositiveIntegerField(max_length=128, verbose_name='Возраст падавана')),
                ('email', models.EmailField(max_length=256, verbose_name='Е-мейл')),
                ('planet', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.planetmodel', verbose_name='Планета обитания')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
        migrations.AlterField(
            model_name='jedimodel',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя джедая'),
        ),
        migrations.AlterField(
            model_name='jedimodel',
            name='surname',
            field=models.CharField(max_length=128, verbose_name='Фамилия джедая'),
        ),
        migrations.DeleteModel(
            name='ParticipantModel',
        ),
    ]
