# Generated by Django 3.1 on 2020-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200823_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='jedimodel',
            name='age',
            field=models.PositiveIntegerField(default=200, verbose_name='Возраст падавана'),
        ),
        migrations.AlterField(
            model_name='padavanmodel',
            name='age',
            field=models.PositiveIntegerField(default=100, verbose_name='Возраст падавана'),
        ),
    ]
