# Generated by Django 3.1 on 2020-08-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200823_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PadavanModel',
            new_name='PadawanModel',
        ),
    ]
