# Generated by Django 3.1 on 2020-08-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200823_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='questions',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='jedimodel',
            name='age',
            field=models.PositiveIntegerField(default=200, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='jedimodel',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='jedimodel',
            name='surname',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='padawanmodel',
            name='age',
            field=models.PositiveIntegerField(default=100, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='padawanmodel',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='padawanmodel',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='padawanmodel',
            name='surname',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
    ]
