# Generated by Django 3.1 on 2020-08-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200824_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='question',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='question',
            field=models.ForeignKey(default=1, max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.questionmodel', verbose_name='Вопрос задания'),
            preserve_default=False,
        ),
    ]
