# Generated by Django 3.1 on 2020-08-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200824_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='questions',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='task',
            field=models.ForeignKey(default=1, max_length=128, on_delete=django.db.models.deletion.CASCADE, to='mainapp.taskmodel', verbose_name='Вопрос задания'),
            preserve_default=False,
        ),
    ]
