# Generated by Django 3.1 on 2020-08-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20200824_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='text',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='padawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.padawanmodel', verbose_name='Отвечавший падаван'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Кратское название вопроса'),
        ),
    ]
