# Generated by Django 3.1 on 2020-08-26 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_jedispadawan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jedispadawan',
            name='padawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.padawanmodel', verbose_name='Падаван джедая'),
        ),
        migrations.AlterField(
            model_name='jedispadawan',
            name='jedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.jedimodel', verbose_name='Джедай'),
        ),
    ]
